#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2024-2026 Sebastien Rousseau
# SPDX-License-Identifier: Apache-2.0 OR MIT
#
# Open (or refresh) a pull request mirroring the wiserone.com quote pool.
#
# Run by .github/workflows/corpus-sync.yml. When scripts/sync_corpus.py
# changes quotes/quotes.json or quotes.csv, this commits both files to
# the branch chore/corpus-sync through the GitHub API (so the commit is
# signed by GitHub and shows as Verified), opens a PR if none is open,
# enables auto-merge, and dispatches the CI pipeline: a PR opened with
# GITHUB_TOKEN does not trigger workflows on its own, but a
# workflow_dispatch does, and its CI Gate check satisfies branch
# protection.
#
# Needs GH_TOKEN and GITHUB_REPOSITORY. Usage: scripts/corpus_sync_pr.sh
set -euo pipefail
shopt -s inherit_errexit

BRANCH=chore/corpus-sync
FILES=(quotes/quotes.json quotes/quotes.csv)
REPO=${GITHUB_REPOSITORY:?GITHUB_REPOSITORY must be set}
cd "$(dirname "$0")/.."

if git diff --quiet -- "${FILES[@]}"; then
  echo "[corpus-sync] corpus already matches wiserone.com; nothing to do"
  exit 0
fi

main_sha=$(gh api "repos/$REPO/git/ref/heads/main" -q .object.sha)

# Start the branch from main each time, so the PR holds exactly one
# up-to-date commit.
if gh api "repos/$REPO/git/ref/heads/$BRANCH" >/dev/null 2>&1; then
  gh api -X PATCH "repos/$REPO/git/refs/heads/$BRANCH" -f sha="$main_sha" -F force=true >/dev/null
else
  gh api -X POST "repos/$REPO/git/refs" -f ref="refs/heads/$BRANCH" -f sha="$main_sha" >/dev/null
fi

additions=$(python3 - "${FILES[@]}" <<'PY'
import base64, json, sys
print(json.dumps([
    {"path": p, "contents": base64.b64encode(open(p, "rb").read()).decode()}
    for p in sys.argv[1:]
]))
PY
)
payload=$(jq -n \
  --arg repo "$REPO" --arg branch "$BRANCH" --arg head "$main_sha" \
  --argjson additions "$additions" \
  '{query: "mutation($input: CreateCommitOnBranchInput!) { createCommitOnBranch(input: $input) { commit { oid } } }",
    variables: {input: {
      branch: {repositoryNameWithOwner: $repo, branchName: $branch},
      expectedHeadOid: $head,
      message: {headline: "chore(corpus): mirror the wiserone.com quote pool",
                body: "Regenerated by scripts/sync_corpus.py from https://wiserone.com/quotes.json, the canonical pool (docs/POLICIES.md#corpus-changes)."},
      fileChanges: {additions: $additions}}}}')
commit=$(gh api graphql --input - <<<"$payload" -q .data.createCommitOnBranch.commit.oid)
if [ -z "$commit" ]; then
  echo "[corpus-sync] FAIL: the commit on $BRANCH was not created" >&2
  exit 1
fi
echo "[corpus-sync] committed $commit on $BRANCH"

pr=$(gh pr list -R "$REPO" --head "$BRANCH" --state open --json url -q '.[0].url // ""')
if [ -z "$pr" ]; then
  pr=$(gh pr create -R "$REPO" --base main --head "$BRANCH" \
    --title "chore(corpus): mirror the wiserone.com quote pool" \
    --body "Automated by the weekly corpus-sync workflow. wiserone.com's pool is canonical; this updates the bundled copy so \`wiserone daily\` keeps selecting the same quote as the site. Merges automatically once the CI Gate passes.")
fi
gh pr merge -R "$REPO" --auto --squash "$pr"
gh workflow run ci.yml -R "$REPO" --ref "$BRANCH"
echo "[corpus-sync] $pr: auto-merge enabled, CI dispatched"
